version: "3"
services:
  backend:
    build: ./backend
    hostname: backend
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    depends_on:
      - mongo
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
  frontend:
    build: ./frontend
    hostname: frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    depends_on:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  mongo:
    image: mongo:7
    hostname: mongo
    ports:
     - "27017:27017"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - mongodb-data:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

volumes:
  mongodb-data:
