version: "3"
services:
  backend:
    build: ./backend
    hostname: wol-backend
    network_mode: "host"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  frontend:
    build: ./frontend
    hostname: wol-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - BACKEND_API=${BACKEND_API}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  mongo:
    image: mongo:7
    hostname: wol-mongo
    ports:
     - "27017:27017"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - mongodb-data:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

volumes:
  mongodb-data:
