package main

import (
	"context"
	"fernandoglatz/wake-on-lan/internal/core/common/utils"
	"fernandoglatz/wake-on-lan/internal/core/common/utils/log"
	"fernandoglatz/wake-on-lan/internal/core/server"
	"fernandoglatz/wake-on-lan/internal/infrastructure/config"

	"github.com/joho/godotenv"
)

// @title			wake-on-lan
// @version			1.0

// @license.name	Apache 2.0
// @license.url		http://www.apache.org/licenses/LICENSE-2.0.html

// @BasePath		/wake-on-lan

// @securityDefinitions.basic	BasicAuth
// @securityDefinitions.apikey	Bearer
// @in 				header
// @name 			X-AUTHORIZATION
// @description     Generated by /authentication

func main() {
	ctx := context.Background()
	godotenv.Load()

	err := config.LoadConfig(ctx)
	if err != nil {
		log.Fatal(ctx).Msg(err.Error())
	}

	err = utils.ConnectToMongoDB(ctx)
	if err != nil {
		log.Fatal(ctx).Msg(err.Error())
	}

	err = server.Setup(ctx)
	if err != nil {
		log.Fatal(ctx).Msg(err.Error())
	}
}
